### ISSUE TITLE
Error: Error getting chaincode code chaincode: Failed to determine platform type: Unknown chaincodeType: NODE

### ISSUE THREAD

**Issue by PieterBogemans** [wearetheledger/fabric-network-boilerplate#4] opened 2018-03-15 10:11 UTC
Na clonen, ./startFabric gerund

```
yarn install v1.5.1
warning ../../../../../package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 59.17s.
yarn run v1.5.1
warning ../../../../../package.json: No license field
$ npm run clean && tsc

> fabric-network-boilerplate@1.0.0 clean /home/pieterbogemans/Desktop/TheLedger/fabric-network-boilerplate/chaincode/node
> rm -rf dist

Done in 8.11s.

# don't rewrite paths for Windows Git Bash users
export MSYS_NO_PATHCONV=1

docker-compose -f docker-compose.yml down
Stopping cli ... done
Stopping peer0.org1.example.com ... done
Stopping ca.example.com ... done
Stopping orderer.example.com ... done
Stopping couchdb ... done
Removing cli ... done
Removing peer0.org1.example.com ... done
Removing ca.example.com ... done
Removing orderer.example.com ... done
Removing couchdb ... done
Removing network net_basic

#remove old images
docker ps -aq -f name=dev- | xargs docker rm | true
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...] [flags]

Remove one or more containers
docker rmi $(docker images dev-* -q) | true
docker images dev-* -q
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...] [flags]

Remove one or more images


docker-compose -f docker-compose.yml up -d ca.example.com orderer.example.com peer0.org1.example.com couchdb
Creating network "net_basic" with the default driver
Creating orderer.example.com
Creating ca.example.com
Creating couchdb
Creating peer0.org1.example.com

# wait for Hyperledger Fabric to start
# incase of errors when running later commands, issue export FABRIC_START_TIMEOUT=<larger number>
export FABRIC_START_TIMEOUT=10
#echo ${FABRIC_START_TIMEOUT}
sleep ${FABRIC_START_TIMEOUT}

# Create the channel
docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp" peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c mychannel -f /etc/hyperledger/configtx/channel.tx
2018-03-15 10:09:48.749 UTC [msp] GetLocalMSP -> DEBU 001 Returning existing local MSP
2018-03-15 10:09:48.750 UTC [msp] GetDefaultSigningIdentity -> DEBU 002 Obtaining default signing identity
2018-03-15 10:09:48.753 UTC [channelCmd] InitCmdFactory -> INFO 003 Endorser and orderer connections initialized
2018-03-15 10:09:48.763 UTC [msp] GetLocalMSP -> DEBU 004 Returning existing local MSP
2018-03-15 10:09:48.763 UTC [msp] GetDefaultSigningIdentity -> DEBU 005 Obtaining default signing identity
2018-03-15 10:09:48.764 UTC [msp] GetLocalMSP -> DEBU 006 Returning existing local MSP
2018-03-15 10:09:48.764 UTC [msp] GetDefaultSigningIdentity -> DEBU 007 Obtaining default signing identity
2018-03-15 10:09:48.764 UTC [msp/identity] Sign -> DEBU 008 Sign: plaintext: 0A88060A074F7267314D535012FC052D...53616D706C65436F6E736F727469756D 
2018-03-15 10:09:48.764 UTC [msp/identity] Sign -> DEBU 009 Sign: digest: 4E289D3EF1248112AF63C20120E6D50E523AE991E2049BC72E68E68953273E9E 
2018-03-15 10:09:48.770 UTC [msp] GetLocalMSP -> DEBU 00a Returning existing local MSP
2018-03-15 10:09:48.770 UTC [msp] GetDefaultSigningIdentity -> DEBU 00b Obtaining default signing identity
2018-03-15 10:09:48.770 UTC [msp] GetLocalMSP -> DEBU 00c Returning existing local MSP
2018-03-15 10:09:48.770 UTC [msp] GetDefaultSigningIdentity -> DEBU 00d Obtaining default signing identity
2018-03-15 10:09:48.770 UTC [msp/identity] Sign -> DEBU 00e Sign: plaintext: 0ABF060A1508021A0608EC8CA9D50522...CF8DE3170DE3FB149EBBBBAD3EF97F18 
2018-03-15 10:09:48.770 UTC [msp/identity] Sign -> DEBU 00f Sign: digest: 208812B5E26CF8FA04EFA0684E61659580018B1B0DB8EC587CF5493465BB576F 
2018-03-15 10:09:48.977 UTC [msp] GetLocalMSP -> DEBU 010 Returning existing local MSP
2018-03-15 10:09:48.977 UTC [msp] GetDefaultSigningIdentity -> DEBU 011 Obtaining default signing identity
2018-03-15 10:09:48.977 UTC [msp] GetLocalMSP -> DEBU 012 Returning existing local MSP
2018-03-15 10:09:48.977 UTC [msp] GetDefaultSigningIdentity -> DEBU 013 Obtaining default signing identity
2018-03-15 10:09:48.977 UTC [msp/identity] Sign -> DEBU 014 Sign: plaintext: 0ABF060A1508021A0608EC8CA9D50522...F808DD7D0F1712080A021A0012021A00 
2018-03-15 10:09:48.977 UTC [msp/identity] Sign -> DEBU 015 Sign: digest: 2A0301858193E36C34C0504D22D5797D27C9E6073EF16AEC5366EFA77EA357D0 
2018-03-15 10:09:49.030 UTC [channelCmd] readBlock -> DEBU 016 Got status: &{NOT_FOUND}
2018-03-15 10:09:49.030 UTC [msp] GetLocalMSP -> DEBU 017 Returning existing local MSP
2018-03-15 10:09:49.030 UTC [msp] GetDefaultSigningIdentity -> DEBU 018 Obtaining default signing identity
2018-03-15 10:09:49.031 UTC [channelCmd] InitCmdFactory -> INFO 019 Endorser and orderer connections initialized
2018-03-15 10:09:49.232 UTC [msp] GetLocalMSP -> DEBU 01a Returning existing local MSP
2018-03-15 10:09:49.232 UTC [msp] GetDefaultSigningIdentity -> DEBU 01b Obtaining default signing identity
2018-03-15 10:09:49.232 UTC [msp] GetLocalMSP -> DEBU 01c Returning existing local MSP
2018-03-15 10:09:49.233 UTC [msp] GetDefaultSigningIdentity -> DEBU 01d Obtaining default signing identity
2018-03-15 10:09:49.233 UTC [msp/identity] Sign -> DEBU 01e Sign: plaintext: 0ABF060A1508021A0608ED8CA9D50522...58606B870C0D12080A021A0012021A00 
2018-03-15 10:09:49.233 UTC [msp/identity] Sign -> DEBU 01f Sign: digest: BC8A0E42828BE4AA93ADA43D5254597AC5EE39C7E9D85B453EA0799581D99F56 
2018-03-15 10:09:49.238 UTC [channelCmd] readBlock -> DEBU 020 Received block: 0
2018-03-15 10:09:49.242 UTC [main] main -> INFO 021 Exiting.....
# Join peer0.org1.example.com to the channel.
docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp" peer0.org1.example.com peer channel join -b mychannel.block
2018-03-15 10:09:49.546 UTC [msp] GetLocalMSP -> DEBU 001 Returning existing local MSP
2018-03-15 10:09:49.547 UTC [msp] GetDefaultSigningIdentity -> DEBU 002 Obtaining default signing identity
2018-03-15 10:09:49.549 UTC [channelCmd] InitCmdFactory -> INFO 003 Endorser and orderer connections initialized
2018-03-15 10:09:49.550 UTC [msp/identity] Sign -> DEBU 004 Sign: plaintext: 0A86070A5C08011A0C08ED8CA9D50510...BDFF058493D71A080A000A000A000A00 
2018-03-15 10:09:49.550 UTC [msp/identity] Sign -> DEBU 005 Sign: digest: EB8191290DC4B0A3AE507F1CCAF096DEC5DAC2B3F903D87955977AB10D7237BA 
2018-03-15 10:09:49.748 UTC [channelCmd] executeJoin -> INFO 006 Peer joined the channel!
2018-03-15 10:09:49.755 UTC [main] main -> INFO 007 Exiting.....
Creating cli
2018-03-15 10:09:52.502 UTC [msp] GetLocalMSP -> DEBU 001 Returning existing local MSP
2018-03-15 10:09:52.507 UTC [msp] GetDefaultSigningIdentity -> DEBU 002 Obtaining default signing identity
2018-03-15 10:09:52.508 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default escc
2018-03-15 10:09:52.508 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 004 Using default vscc
Error: Error getting chaincode code chaincode: Failed to determine platform type: Unknown chaincodeType: NODE
Usage:
  peer chaincode install [flags]

Flags:
  -c, --ctor string      Constructor message for the chaincode in JSON format (default "{}")
  -l, --lang string      Language the chaincode is written in (default "golang")
  -n, --name string      Name of the chaincode
  -p, --path string      Path to chaincode
  -v, --version string   Version of the chaincode specified in install/instantiate/upgrade commands

Global Flags:
      --cafile string              Path to file containing PEM-encoded trusted certificate(s) for the ordering endpoint
      --logging-level string       Default logging level and overrides, see core.yaml for full syntax
  -o, --orderer string             Ordering service endpoint
      --test.coverprofile string   Done (default "coverage.cov")
      --tls                        Use TLS when communicating with the orderer endpoint

```

**Comment by Superjo149** [comment] 2018-03-15 11:19
Issue is caused by using the Fabric 1.0.0 images, which do not include nodejs chaincode yet. This can be resolved by running the following script `./scripts/fabric-preload.sh`. Optionally the script can also be run with a specific version like so `./scripts/fabric-preload.sh 1.0.0`

**Closed by Superjo149** 2018-03-15 11:19 UTC

**Comment by GaJain** [comment] 2019-03-31 06:37
0

I am new to Hyperledger Fabric and going thru their study tutorial https://hyperledger-fabric.readthedocs.io/en/latest/write_first_app.html . Issue : I made changes in query.js and invoke.js to replace local host with my IP Address which I reverted back to original . Now when I run startFabric.sh script , I am getting following error : " Error: error getting chaincode code fabcar: failed to determine platform type: Unknown chaincodeType: UNDEFINED " . I have googled the issue whole day but still unable to solve . Please let me know how I may solve this issue .
